# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 23:17
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wish'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wish',
            managers=[
                ('wishMgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='user',
            new_name='users',
        ),
    ]
