# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20161119_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='creator',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
